title: "Je'm | OHLUCINDA | independent music"
description: "Song lyrics and independent music"
url: "https://ohlucinda.github.io"
baseurl: "/jemmusic"

theme: minima

kramdown:
  input: GFM
  hard_wrap: true
