title: "Je'm | Lyrics"
description: "Song lyrics and independent music"
url: "https://jemlyrics.ohlucinda.com"
baseurl: ""

theme: minima

kramdown:
  input: GFM
  hard_wrap: true

permalink: /:title/
