title: "Je'm | Lyrics"
description: "Song lyrics and independent music"
url: "https://ohlucinda.github.io"
baseurl: "/jemmusic"

logo: /favicon.ico

theme: minima

kramdown:
  input: GFM
  hard_wrap: true
